import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    overlay: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContainer: {
      backgroundColor: '#FFFFFF',
      borderRadius: 10,
      width: '90%',
      maxWidth: 400,
      padding: 16,
      maxHeight: '80%',
    },
    modalContainerExpanded: {
      height: '90%',
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 16,
    },
    closeButton: {
      padding: 8,
    },
    closeIcon: {
      width: 24,
      height: 24,
    },
    title: {
      fontSize: 18,
      fontWeight: '600',
      color: '#111827',
      marginLeft: 8,
    },
    shopDetails: {
      backgroundColor: '#FFFDD8',
      borderRadius: 8,
      padding: 16,
      marginBottom: 24,
    },
    shopName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#111827',
      marginBottom: 8,
    },
    paymentInfo: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    dueDate: {
      fontSize: 14,
      color: '#4B5563',
    },
    amount: {
      fontSize: 18,
      fontWeight: '600',
      color: '#111827',
    },
    paymentTypeContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 24,
    },
    paymentTypeButton: {
      flex: 1,
      alignItems: 'center',
      backgroundColor: '#F3F4F6',
      padding: 12,
      borderRadius: 8,
      marginHorizontal: 4,
      borderWidth: 1,
      borderColor: 'transparent',
    },
    selectedPaymentType: {
      borderColor: '#EF4444',
      backgroundColor: '#F3F4F6',
    },
    paymentTypeText: {
      fontSize: 12,
      color: '#374151',
      marginTop: 4,
    },
    selectedPaymentTypeText: {
      color: '#EF4444',
      fontWeight: '500',
    },
    amountContainer: {
      marginBottom: 24,
    },
    amountLabel: {
      fontSize: 14,
      color: '#374151',
      marginBottom: 8,
    },
    amountInputWrapper: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    amountInputContainer: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F9FAFB',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      paddingHorizontal: 12,
    },
    currencyLabel: {
      fontSize: 16,
      color: '#374151',
      marginRight: 8,
    },
    amountInput: {
      flex: 1,
      height: 48,
      fontSize: 16,
      color: '#111827',
  
    },
    denominationButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#F3F4F6',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      paddingHorizontal: 12,
      height: 48,
      gap: 8,
    },
    denominationText: {
      fontSize: 14,
      color: '#374151',
    },
    chequeFieldsContainer: {
      marginTop: 8,
      marginBottom: 24,
      borderTopWidth: 1,
      borderTopColor: '#E5E7EB',
      paddingTop: 16,
    },
    fieldRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
      gap: 8,
    },
    fieldLabel: {
      fontSize: 14,
      color: '#374151',
      width: 120,
    },
    required: {
      color: '#EF4444',
      marginLeft: 2,
    },
    textInput: {
      flex: 1,
      height: 40,
      backgroundColor: '#F9FAFB',
      borderRadius: 4,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      paddingHorizontal: 12,
      fontSize: 14,
      color: '#111827',
    },
    dateInput: {
      flex: 1,
      height: 40,
      backgroundColor: '#E5E7EB',
      borderRadius: 4,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      paddingHorizontal: 12,
      justifyContent: 'center',
    },
    dateText: {
      fontSize: 14,
      color: '#111827',
    },
    uploadButton: {
      flex: 1,
      height: 40,
      backgroundColor: '#FFFFFF',
      borderRadius: 4,
      borderWidth: 1,
      borderColor: '#E5E7EB',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    uploadText: {
      fontSize: 14,
      color: '#6366F1',
    },
    submitButton: {
      backgroundColor: '#10B981',
      borderRadius: 8,
      padding: 16,
      alignItems: 'center',
    },
    submitButtonText: {
      fontSize: 14,
      fontWeight: '600',
      color: '#FFFFFF',
    },
    imageUploadContainer: {
      flex: 1,
    },
    previewImage: {
      width: '100%',
      height: 120,
      borderRadius: 4,
      marginBottom: 8,
    },
    retakeButton: {
      backgroundColor: '#F3F4F6',
      padding: 8,
      borderRadius: 4,
      alignItems: 'center',
    },
    retakeText: {
      color: '#374151',
      fontSize: 14,
    },
    cameraContainer: {
      flex: 1,
      backgroundColor: 'black',
    },
    camera: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    cameraControls: {
      position: 'absolute',
      bottom: 40,
      left: 0,
      right: 0,
      flexDirection: 'row',
      justifyContent: 'space-around',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    closeCamera: {
      padding: 15,
      backgroundColor: 'rgba(0,0,0,0.6)',
      borderRadius: 8,
    },
    closeCameraText: {
      color: 'white',
      fontSize: 16,
    },
    captureButton: {
      alignSelf: 'center',
      width: 70,
      height: 70,
      borderRadius: 35,
      backgroundColor: 'rgba(255, 255, 255, 0.3)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    captureCircle: {
      width: 54,
      height: 54,
      borderRadius: 27,
      backgroundColor: 'white',
    },
    blurContainer: {
      flex: 1,
    },
  }); 

  export default styles; 